---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-adminer
  labels:
    app: {{ template "infra.name" . }}-adminer
    chart: {{ template "infra.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "infra.name" . }}-adminer
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "infra.name" . }}-adminer
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ printf "%s:%s" ( .Values.adminer.image.repository | default "adminer" ) ( .Values.adminer.image.tag | toString ) }}
          imagePullPolicy: {{ .Values.adminer.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
