---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mailer
  labels:
    app: {{ template "infra.name" . }}-mailer
    chart: {{ template "infra.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: smtp
      port: 25
      targetPort: smtp
      protocol: TCP
  selector:
    app: {{ template "infra.name" . }}-mailer
    release: {{ .Release.Name }}
