---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress

---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-elasticsearch-internal
spec:
  podSelector:
    matchLabels:
      app: elasticsearch
      release: {{ .Release.Name }}
  ingress:
    - from:
      - podSelector:
          app: elasticsearch
          release: {{ .Release.Name }}

---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-fluentd-elasticsearch
spec:
  podSelector:
    matchLabels:
      app: elasticsearch
      component: client
      release: {{ .Release.Name }}
  ingress:
    - from:
      - podSelector:
          app: kibana
          release: {{ .Release.Name }}
      - podSelector:
          app: {{ .Release.Name }}-fluentd-elasticsearch
          release: {{ .Release.Name }}
